---
title: "KubernetesClientException: An error has occurred"
categories:
  - Java
date: 2025-05-16 16:15:48
tags:
  - kubernetes
  - java
  - istio
---

## 问题背景

最近在升级kubernetes的istio服务,在使用java客户端访问kubernetes集群时,出现如下异常:

```bash
2025-05-16T11:20:44.075338929+08:00 stdout F io.fabric8.kubernetes.client.KubernetesClientException: An error has occurred.
2025-05-16T11:20:44.075341454+08:00 stdout F at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:129) ~[kubernetes-client-api-6.5.0.jar!/:na]
2025-05-16T11:20:44.075343598+08:00 stdout F at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:122) ~[kubernetes-client-api-6.5.0.jar!/:na]
2025-05-16T11:20:44.075345642+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:551) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:20:44.075348097+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleResponse(OperationSupport.java:566) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:20:44.075349519+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.handleCreate(OperationSupport.java:350) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:20:44.075350872+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:707) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:20:44.075352254+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.BaseOperation.handleCreate(BaseOperation.java:93) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:20:44.075370869+08:00 stdout F at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384) ~[na:1.8.0_402]
2025-05-16T11:20:44.075373304+08:00 stdout F at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[na:1.8.0_402]
2025-05-16T11:20:44.075375979+08:00 stdout F at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[na:1.8.0_402]
2025-05-16T11:20:44.075378274+08:00 stdout F at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[na:1.8.0_402]
2025-05-16T11:20:44.075380548+08:00 stdout F at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:1.8.0_402]
2025-05-16T11:20:44.075382912+08:00 stdout F at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[na:1.8.0_402]
2025-05-16T11:20:44.075386399+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:200) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:20:44.075389204+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableListImpl.java:60) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:20:44.075391779+08:00 stdout F at com.taimeitech.middle.cicd.command.service.impl.KubectlApplyServiceImpl.createOrReplace(KubectlApplyServiceImpl.java:64) ~[classes!/:0.0.1-SNAPSHOT]
2025-05-16T11:20:44.075394224+08:00 stdout F at com.taimeitech.middle.cicd.command.websocket.ApplicationRunnerImpl$1.applyAndSendMsg(ApplicationRunnerImpl.java:124) [classes!/:0.0.1-SNAPSHOT]
......

2025-05-16T11:22:34.417521853+08:00 stdout F at org.java_websocket.WebSocketImpl.decode(WebSocketImpl.java:233) [Java-WebSocket-1.5.3.jar!/:na]
2025-05-16T11:22:34.417522955+08:00 stdout F at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:516) [Java-WebSocket-1.5.3.jar!/:na]
2025-05-16T11:22:34.417527434+08:00 stdout F at java.lang.Thread.run(Thread.java:750) [na:1.8.0_402]
2025-05-16T11:22:34.417528586+08:00 stdout F Caused by: java.util.concurrent.TimeoutException: null
2025-05-16T11:22:34.417530038+08:00 stdout F at java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1784) ~[na:1.8.0_402]
2025-05-16T11:22:34.417531301+08:00 stdout F at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928) ~[na:1.8.0_402]
2025-05-16T11:22:34.417532523+08:00 stdout F at io.fabric8.kubernetes.client.dsl.internal.OperationSupport.waitForResult(OperationSupport.java:528) ~[kubernetes-client-6.5.0.jar!/:na]
2025-05-16T11:22:34.417533866+08:00 stdout F ... 29 common frames omitted
```

## 问题分析

注意到日志中出现了`2025-05-16T11:22:34.417528586+08:00 stdout F Caused by: java.util.concurrent.TimeoutException: null`,这是因为在等待kubernetes集群响应时,超时了，首先想到的解决办法是增加超时时间,

```java
 Config config = new ConfigBuilder()
                .withConnectionTimeout(20000)
                .withRequestTimeout(20000)
                .build();
        try (KubernetesClient k8s = new KubernetesClientBuilder()
                .withConfig(config)
                .build()) {
                    //省略其他......
                }
```

再次执行之后,出现了新的错误

```bash
Failure executing: PUT at: https://192.168.0.1:443/apis/networking.istio.io/v1beta1/namespaces/middle/destinationrules/pdf-service-default. Message: Internal error occurred: failed calling webhook "validation.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found. Received status: Status(apiVersion=v1, code=500, details=StatusDetails(causes=[StatusCause(field=null, message=failed calling webhook "validation.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found, reason=null, additionalProperties={})], group=null, kind=null, name=null, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=Internal error occurred: failed calling webhook "validation.istio.io": failed to call webhook: Post "https://istiod.istio-system.svc:443/validate?timeout=10s": service "istiod" not found, metadata=ListMeta(_continue=null, remainingItemCount=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=InternalError, status=Failure, additionalProperties={}).
```

也就是说之前的超时错误只是表面现象,真正的原因是kubernetes集群中升级后的istio服务无法访问到,所以超时了.

## 解决方案

1. 检查kubernetes集群中相关的istio服务,修改为正确的配置.
